apiVersion: apps/v1
kind: Deployment
metadata:
  name: storeecommerceapp
spec:
  selector:
    matchLabels:
      app: storeecommerceapp
  replicas: 1
  template:
    metadata:
      labels:
        app: storeecommerceapp
    spec:
      containers:
        - name: storeecommerceapp
          image: omerceltikk/storeecommerceapp:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: 200m
              memory: 1Gi
            limits:
              cpu: 1
              memory: 1Gi